"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var BaseLayers;
(function (BaseLayers) {
    BaseLayers[BaseLayers["BASE"] = 1] = "BASE";
    BaseLayers[BaseLayers["TURIST"] = 2] = "TURIST";
    BaseLayers[BaseLayers["OPHOTO"] = 3] = "OPHOTO";
    BaseLayers[BaseLayers["HYBRID"] = 4] = "HYBRID";
    BaseLayers[BaseLayers["HISTORIC"] = 5] = "HISTORIC";
    BaseLayers[BaseLayers["BIKE"] = 6] = "BIKE";
    BaseLayers[BaseLayers["TRAIL"] = 7] = "TRAIL";
    BaseLayers[BaseLayers["OPHOTO0203"] = 8] = "OPHOTO0203";
    BaseLayers[BaseLayers["OPHOTO0406"] = 9] = "OPHOTO0406";
    BaseLayers[BaseLayers["OBLIQUE"] = 12] = "OBLIQUE";
    BaseLayers[BaseLayers["SMART_BASE"] = 14] = "SMART_BASE";
    BaseLayers[BaseLayers["SMART_OPHOTO"] = 15] = "SMART_OPHOTO";
    BaseLayers[BaseLayers["SMART_TURIST"] = 16] = "SMART_TURIST";
    BaseLayers[BaseLayers["RELIEF"] = 17] = "RELIEF";
    BaseLayers[BaseLayers["TURIST_WINTER"] = 19] = "TURIST_WINTER";
    BaseLayers[BaseLayers["SMART_WINTER"] = 20] = "SMART_WINTER";
    BaseLayers[BaseLayers["SUMMER"] = 21] = "SUMMER";
    BaseLayers[BaseLayers["SMART_SUMMER"] = 22] = "SMART_SUMMER";
    BaseLayers[BaseLayers["GEOGRAPHY"] = 23] = "GEOGRAPHY";
    BaseLayers[BaseLayers["OPHOTO1012"] = 24] = "OPHOTO1012";
    BaseLayers[BaseLayers["HYBRID_SPARSE"] = 25] = "HYBRID_SPARSE";
    BaseLayers[BaseLayers["OPHOTO1415"] = 26] = "OPHOTO1415";
    BaseLayers[BaseLayers["BASE_NEW"] = 27] = "BASE_NEW";
    BaseLayers[BaseLayers["TURIST_NEW"] = 28] = "TURIST_NEW";
})(BaseLayers || (BaseLayers = {}));
exports.default = BaseLayers;
//# sourceMappingURL=BaseLayers.js.map